Keelin/vectornator changes
LinearityGmbH/unsplash-photopicker-ios pull request #1
Opened 2020-06-04 09:45 UTC by lucaangeletti

These are the changes required to get Unsplash working correctly with Vectornator.

2020-06-04 09:47 UTC, lucaangeletti commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Controllers/UnsplashPhotoPicker.swift
> +        //dismiss(animated: true, completion: nil)
@GweebarraRover Usually we delete the unused code.

@pavlolinearity Should we do it even on this forked repo? Or in this case makes sense leaving the old code commented maybe?

2020-06-04 09:48 UTC, lucaangeletti commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Controllers/UnsplashPhotoPicker.swift
> +        //dismiss(animated: true, completion: nil)
@GweebarraRover Same here 👆and also below 👇.

2020-06-04 09:48 UTC, lucaangeletti reviewed
Please see my comments.

2020-06-09 19:19 UTC, pmattos requested changes

2020-06-09 19:19 UTC, pmattos commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Controllers/UnsplashPhotoPickerViewController.swift
> -
Please let's try to reduce the number of changes... can we leave this method as is?

2020-06-09 19:19 UTC, pmattos commented on UnsplashPhotoPicker/UnsplashPhotoPicker/Classes/Controllers/UnsplashPhotoPickerViewController.swift
> -
Please let's try to reduce the number of changes... can we leave this method as is?

2020-06-09 19:20 UTC, pmattos commented
@GweebarraRover Please check my review comments...

2020-06-12 15:46 UTC, pmattos commented
@GweebarraRover @lucaangeletti To be clear guys, we need to merge this *before* [PR 337](https://github.com/LinearityGmbH/Vectornator/pull/337)... otherwise the submodule commit (ie, for `Frameworks/UnsplashPhotopicker`) won't reflect the right one. The submodule this to point to the commit created by merging this PR...

2020-06-12 16:30 UTC, GweebarraRover commented
Yes, I will revert the deleted code and get this PR updated. Then it's simply pointing the unsplash branch submodule to this and it will be finished.

2020-06-22 13:07 UTC, merged